INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (1, 1, 1, 'Fruta GTBC', 4400, false, '2024-04-05');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (2, 1, 1, 'Gasolina', 20000, false, '2024-04-05');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (3, 1, 1, 'Tenis', 37900, false, '2024-04-06');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (4, 1, 1, 'Despensa Chedraui', 17000, false, '2024-04-06');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (5, 1, 1, 'Desayuno Seven Cineteca', 11000, false, '2024-04-07');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (6, 1, 1, 'Tiendita', 3800, false, '2024-04-08');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (7, 1, 1, 'Farmacia', 4100, false, '2024-04-08');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (8, 1, 1, 'Tiendita', 9000, false, '2024-04-08');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (9, 1, 1, 'Agua', 2500, false, '2024-04-10');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (10, 1, 1, 'Comida', 4900, false, '2024-04-10');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (11, 1, 1, 'Comida GTBC', 5000, false, '2024-04-11');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (12, 1, 1, 'Cafeteria Tierra Garat', 6800, false, '2024-04-12');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (13, 1, 1, 'Sushi Factory', 63300, false, '2024-04-12');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (14, 1, 1, 'CafÃ©', 3500, false, '2024-04-13');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (15, 1, 1, 'Agua', 1200, false, '2024-04-13');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (16, 1, 1, 'Gasolina', 20000, false, '2024-04-13');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (17, 1, 1, 'Comida UPIITA', 7800, false, '2024-04-16');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (18, 1, 1, 'Despensa Chedraui', 36000, false, '2024-04-16');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (19, 1, 1, 'Otros', 18100, false, '2024-04-18');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (20, 1, 1, 'Helados', 10900, false, '2024-04-06');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (21, 1, 1, 'Comida', 2800, false, '2024-04-18');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (22, 1, 1, 'Cursos InglÃ©s', 334600, false, '2024-04-20');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (23, 1, 1, 'Viaje Uber Nestor-Casa', 17200, false, '2024-04-20');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (24, 1, 1, 'Cita Valeria 21 Abril', 31000, false, '2024-04-21');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (25, 1, 1, 'Cita Valeria Comida 21 Abril', 51700, false, '2024-04-21');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (26, 1, 1, 'Gasolina', 29700, false, '2024-04-22');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (27, 1, 1, 'Internet', 2000, false, '2024-04-22');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (28, 1, 1, 'Comida UPIITA', 3000, false, '2024-04-23');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (29, 1, 1, 'Gym', 36900, false, '2024-04-23');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (30, 1, 1, 'Regalo Valeria', 85800, false, '2024-04-24');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (31, 1, 1, 'Despensa Chedraui', 42300, false, '2024-04-24');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (32, 1, 1, 'Comida con pannas tacos de pescado', 13900, false, '2024-04-24');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (33, 1, 1, 'Farmacia Pastilla', 6500, false, '2024-04-06');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (35, 1, 1, 'Cita Valeria, Compras', 93000, false, '2024-04-26');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (36, 1, 1, 'Oxxo', 1300, false, '2024-04-06');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (37, 1, 1, 'Palomitas Cineteca', 18700, false, '2024-04-07');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (38, 1, 1, 'Churros Cineteca', 3800, false, '2024-04-07');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (39, 1, 1, 'Boletos Cineteca', 14000, false, '2024-04-07');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (51, 1, 1, 'Refrigerador Axel', 280000, false, '2024-04-15');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (40, 1, 1, 'agua', 900, false, '2024-04-28');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (41, 1, 1, 'Lucky sushi', 25300, false, '2024-04-28');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (42, 1, 1, 'Despensa', 98500, false, '2024-04-28');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (43, 1, 1, 'Despensa', 5000, false, '2024-04-30');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (44, 1, 1, 'Despensa coreana', 31700, false, '2024-05-01');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (45, 1, 1, 'Chedraui', 14540, false, '2024-05-02');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (46, 1, 1, 'Tienda', 8150, false, '2024-05-03');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (47, 1, 1, 'Compras después del curso', 5800, false, '2024-05-04');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (48, 1, 1, 'Cafe mientras espero mi moto', 4500, false, '2024-05-04');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (49, 1, 1, 'Antojos en el sams', 11150, false, '2024-05-05');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (50, 1, 1, 'Temu', 64320, false, '2024-05-06');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (52, 1, 1, 'Promos cine', 28900, false, '2024-05-07');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (53, 1, 1, 'Fruta con yogurt', 3400, false, '2024-05-09');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (54, 1, 1, 'Pescado y camarones', 25300, false, '2024-05-09');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (55, 1, 1, 'Chilaquiles en Polanco', 5000, false, '2024-05-10');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (90, 1, 1, 'Sams club ice', 13809, false, '2024-05-26');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (57, 1, 1, 'Home office en antara cafe polanco', 64100, false, '2024-05-10');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (58, 1, 1, 'Desayuno esperanza', 30500, false, '2024-05-11');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (59, 1, 1, 'Oxxo the Anglo', 5200, false, '2024-05-11');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (60, 1, 1, 'Despensa Sams', 26495, false, '2024-05-05');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (61, 1, 1, 'Home office starbucks fortuna', 16300, false, '2024-05-02');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (62, 1, 1, 'iPhone 12 - 1', 86243, false, '2024-05-05');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (63, 1, 1, 'Helado Flotante en la escuela', 3500, false, '2024-05-14');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (64, 1, 1, 'Helado Flotante en la escuela', 3500, false, '2024-05-13');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (65, 1, 1, 'Helados para mis papas', 10500, false, '2024-05-12');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (66, 1, 1, 'Zapatos de mama - 1', 43334, false, '2024-05-12');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (67, 1, 1, 'Peda - Uber regreso', 22990, false, '2024-05-18');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (68, 1, 1, 'Peda - chelas', 51000, false, '2024-05-18');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (69, 1, 1, 'Peda - Uber ida', 16990, false, '2024-05-18');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (70, 1, 1, 'Cursos udemy', 19900, false, '2024-05-15');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (71, 1, 1, 'recarga', 20000, false, '2024-05-17');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (72, 1, 1, 'Despensa', 23501, false, '2024-05-16');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (73, 1, 1, 'Valeria Sushi', 31247, false, '2024-05-16');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (74, 1, 1, 'I love k food', 56300, false, '2024-05-17');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (75, 1, 1, 'Chez vous time cafe', 79800, false, '2024-05-17');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (76, 1, 1, 'test', 10567, false, '2024-05-20');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (77, 1, 1, 'Materiales Moto', 10500, false, '2024-05-28');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (78, 1, 1, 'desayuno gtbc', 6800, false, '2024-05-28');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (79, 1, 1, 'Comida upiita', 7000, false, '2024-05-20');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (80, 1, 1, 'despensa tienda', 2900, false, '2024-05-20');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (81, 1, 1, 'Aguas en concierto de molotov', 4500, false, '2024-05-21');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (82, 1, 1, 'Tacos molotov', 45900, false, '2024-05-21');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (83, 1, 1, 'Chamarra de cuidado con el perro', 39900, false, '2024-05-22');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (84, 1, 1, 'Helados Valeria', 16400, false, '2024-05-22');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (85, 1, 1, 'Cafe starbucks', 5700, false, '2024-05-22');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (86, 1, 1, 'Starbucks con Valeria', 18300, false, '2024-05-23');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (87, 1, 1, 'Panaderia con Valeria', 5000, false, '2024-05-23');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (88, 1, 1, 'Terapia', 69900, false, '2024-05-27');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (89, 1, 1, 'Metrobus', 600, false, '2024-05-25');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (91, 1, 1, 'The Anglo Junio - Julio', 334600, false, '2024-06-01');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (92, 1, 1, 'Chocolate Anglo', 5800, false, '2024-06-01');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (93, 1, 1, 'Desayuno esperanza', 24700, false, '2024-06-01');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (94, 1, 1, 'Pastilla Valeria', 13900, false, '2024-06-01');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (95, 1, 1, 'Despensa Chedraui', 63716, false, '2024-05-31');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (96, 1, 1, 'Helados Valeria', 20000, false, '2024-05-29');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (97, 1, 1, 'Farmacia', 20000, false, '2024-05-29');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (98, 1, 1, 'Nomina', 1022756, true, '2024-05-30');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (99, 1, 1, 'Apple almacenamiento', 4900, false, '2024-05-31');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (100, 1, 1, 'I love k food', 52200, false, '2024-06-02');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (101, 1, 1, 'comida', 3500, false, '2024-06-03');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (102, 1, 1, 'Comida upiita', 2500, false, '2024-06-03');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (103, 1, 1, 'Terapia', 69900, false, '2024-06-04');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (104, 1, 1, 'pollo', 13500, false, '2024-06-04');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (105, 1, 1, 'Comida upiita', 4300, false, '2024-06-04');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (106, 1, 1, 'Gasolina', 20000, false, '2024-06-04');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (107, 1, 1, 'Comida upiita', 3500, false, '2024-06-05');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (108, 1, 1, 'Farmacia pastilla dia sig Valeria', 8800, false, '2024-06-06');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (109, 1, 1, 'Chillis reforma', 38230, false, '2024-06-06');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (110, 1, 1, 'Farmacia Prueba embarazo Valeria', 34500, false, '2024-06-08');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (111, 1, 1, 'Casa de toño Valeria', 29400, false, '2024-06-08');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (112, 1, 1, 'Prueba embarazo', 5700, false, '2024-06-08');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (113, 1, 1, 'Comida upiita', 3500, false, '2024-06-10');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (114, 1, 1, 'Sams club despensa', 44999, false, '2024-06-11');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (115, 1, 1, 'Sams club despensa', 1000, false, '2024-06-11');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (116, 1, 1, 'Comida upiita', 2500, false, '2024-06-12');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (117, 1, 1, 'Ropa shorts', 24900, false, '2024-06-13');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (118, 1, 1, 'Ropa shorts', 21680, false, '2024-06-13');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (119, 1, 1, 'Gasolina', 28152, false, '2024-06-13');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (120, 1, 1, 'Comida Ford', 3800, false, '2024-06-13');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (121, 1, 1, 'Cita Valeria Monumento', 78450, false, '2024-06-14');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (122, 1, 1, 'Chedraui Regalos', 99995, false, '2024-06-14');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (123, 1, 1, 'Cita Valeria Evento Lancome', 71428, false, '2024-06-16');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (124, 1, 1, 'Sams club despensa', 52684, false, '2024-06-17');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (125, 1, 1, 'Medicina', 10500, false, '2024-06-18');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (126, 1, 1, 'Chillis Valeria', 51300, false, '2024-06-18');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (127, 1, 1, 'Comida upiita', 1800, false, '2024-06-19');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (128, 1, 1, 'Reserva Acuario Michin Valeria', 71800, false, '2024-06-20');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (129, 1, 1, 'cafe anglo', 2700, false, '2024-06-22');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (130, 1, 1, 'Cubo rubik', 5250, false, '2024-06-22');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (131, 1, 1, 'agua', 4800, false, '2024-06-22');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (132, 1, 1, 'Chedraui', 7400, false, '2024-07-13');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (133, 1, 1, 'Cine Hermanas', 16500, false, '2024-07-13');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (134, 1, 1, 'Cafesito', 4000, false, '2024-07-13');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (135, 1, 1, 'Ropa 1 de 3 (meses sin intereses)', 90030, false, '2024-07-13');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (136, 1, 1, 'Cita valeria', 53680, false, '2024-07-11');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (137, 1, 1, 'Pollo rostizado', 13700, false, '2024-07-10');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (138, 1, 1, 'Baguettes esperanza', 24700, false, '2024-07-09');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (139, 1, 1, 'Panaderia', 13000, false, '2024-07-09');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (140, 1, 1, 'Meatme napoles', 17700, false, '2024-07-07');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (141, 1, 1, 'Don porfirio', 10600, false, '2024-07-06');
INSERT INTO finances.public.movements (id, user_id, category_id, description, quantity, movement_type, expense_date) VALUES (142, 1, 1, 'Didi', 25800, false, '2024-07-05');